// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class CourseOrder
    {
        public int OrderId { get; set; }
        public int? CandidateId { get; set; }
        public int? CourseId { get; set; }
        public DateTime? Buyingtime { get; set; }
        public bool? Vaild { get; set; }
    }
}