// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Enterprise
    {
        public int EnterpriseId { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Category { get; set; }
        public string CompanyName { get; set; }
        public string UniformNumbers { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public TimeSpan? OpeningHours { get; set; }
        public string Address { get; set; }
        public string Principal { get; set; }
        public string ContactPhone { get; set; }
        public TimeSpan? ContactTime { get; set; }
        public string Email { get; set; }
        public string Info { get; set; }
        public string Img { get; set; }
    }
}