// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Interest
    {
        public int Id { get; set; }
        public int? CandidateId { get; set; }
        public int? EnterpriseId { get; set; }
        public int? VacancyId { get; set; }
        public int? InterestStatus { get; set; }
    }
}