// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Platform
    {
        public int ArticleId { get; set; }
        public string ArticleName { get; set; }
        public int? AuthorId { get; set; }
        public string Contents { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}