// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string Name { get; set; }
        public string Categories { get; set; }
        public DateTime? EntryTime { get; set; }
        public string Experience { get; set; }
        public bool? Working { get; set; }
        public string Img { get; set; }
        public string Intro { get; set; }
    }
}