// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Vacancy
    {
        public int VacancyId { get; set; }
        public string WorkName { get; set; }
        public int? EnterpriseId { get; set; }
        public string Category { get; set; }
        public string WorkPlace { get; set; }
        public string WorkTime { get; set; }
        public int? Salary { get; set; }
        public bool? FullPartTime { get; set; }
        public string Shift { get; set; }
        public int? Seniority { get; set; }
        public string WorkContent { get; set; }
        public string WorkReqire { get; set; }
        public DateTime? Updatetime { get; set; }
        public bool? Valid { get; set; }
    }
}