// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class CandidateCv
    {
        public int CandidateCvid { get; set; }
        public string Cvsource { get; set; }
        public int? CandidateId { get; set; }
        public int? Cvid { get; set; }
    }
}